name: 'Equinix-Metal-Delete-Action'

on:
  workflow_dispatch:
    inputs:
        PROJECT_ID:
          description: 'Metal Project ID'     
          required: true
          default: 'dummy_project_id'
#        PROJECT_TOKEN:
#            description: 'Metal Project Token'     
#            required: true
#            default: 'dummy_project_token'
        Delete_Project:
            description: 'Delete the Project'     
            required: true
            default: 'false'

# env:
#  PROJECT_ID: ${{ secrets.METAL_PROJECT_ID }}
#  PROJECT_TOKEN: ${{ secrets.METAL_PROJECT_TOKEN }}

jobs:
  destroy-metal-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup the Device
        uses: equinix-labs/metal-sweeper-action@main
        with:
          authToken: ${{ secrets.METAL_AUTH_TOKEN }}
          projectID: ${{ github.event.inputs.PROJECT_ID }}
          keepProject: ${{ github.event.inputs.Delete_Project }} # Set to false to delete the project
