name: 'Equinix-Metal-Delete-Action'

on:
  workflow_dispatch:
    inputs:
        PROJECT_ID:
          description: 'Metal Project ID'     
          required: true
          default: 'dummy_project_id'

        Keep_Project:
            description: 'Keep the Project'     
            required: true
            default: 'false'

jobs:
  destroy-metal-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Device and Project Cleanup
        uses: equinix-labs/metal-sweeper-action@main
        with:
          authToken: ${{ secrets.METAL_AUTH_TOKEN }}
          projectID: ${{ github.event.inputs.PROJECT_ID }}
          keepProject: ${{ github.event.inputs.Keep_Project }} # Set to false to delete the project
