# This GitHub Actions workflow, named 'Equinix-Metal-Actions-All-Demo', 
# It is designed to create a temporary project on Equinix Metal, 
# Creates a device in that project and then display the project's SSH keys and ID
# Finally delete the project and device. 

# The workflow is triggered manually using the workflow_dispatch event.
name: 'Equinix-Metal-Actions-All-Demo'

on:
  workflow_dispatch:

jobs:
  manage-metal-project-device:
    runs-on: ubuntu-latest
    steps:
    - name: Create temporary project
      id: metal-project
      uses: equinix-labs/metal-project-action@main
      with:
        userToken: ${{ secrets.METAL_AUTH_TOKEN }}
    - name: Use the Project SSH Key outputs (display it)
      run: |
        echo $PROJECT_PRIVATE_SSH_KEY
        echo $PROJECT_PUBLIC_SSH_KEY
      env:
        PROJECT_PRIVATE_SSH_KEY: ${{ steps.metal-project.outputs.projectSSHPrivateKeyBase64 }}
        PROJECT_PUBLIC_SSH_KEY: ${{ steps.metal-project.outputs.projectSSHPublicKey }}
    - name: Use the Project ID outputs (display it)
      run: |
        echo Equinix Metal Project "$PROJECT_NAME" has ID "$PROJECT_ID"
      env:
        PROJECT_ID: ${{ steps.metal-project.outputs.projectID }}
        PROJECT_NAME: ${{ steps.metal-project.outputs.projectName }}
    - name: Create Runner SSH key and Add to Equinix Project
      run: |
          sudo apt update
          sudo apt install jq -y
  
          mkdir -p ~/.ssh/
          # ssh-keygen -q -t rsa -b 4096 -C "gh-user" -N '' -f ~/.ssh/id_rsa <<<y >/dev/null 2>&1
          ssh-keygen -q -t rsa -b 4096 -N '' -f ~/.ssh/id_rsa <<<y >/dev/null 2>&1
          SSH_PUB_KEY=`cat ~/.ssh/id_rsa.pub`
  
          jq_out=`jq -n --arg sshpubkey "$SSH_PUB_KEY" '{"label": "runner ssh key", "key": $sshpubkey}'`
  
          curl -X POST -H "Content-Type: application/json" -H "X-Auth-Token: ${{ secrets.METAL_AUTH_TOKEN }}" "https://api.equinix.com/metal/v1/projects/${{ steps.metal-project.outputs.projectID }}/ssh-keys" -d "$jq_out"
  
    - name: Create device in temporary project
      id: metal-device
      uses: equinix-labs/metal-device-action@main
      continue-on-error: true
      with:
        metal_auth_token: ${{ steps.metal-project.outputs.projectToken }}
        metal_project_id: ${{ steps.metal-project.outputs.projectID }}
        metro: da
        plan: m3.small.x86
        os: ubuntu_22_04
    - name: SSH into Metal Device and Display CloudInit Logs
      run: |
        ssh -o StrictHostKeyChecking=no -tt root@$${{ steps.metal-device.outputs.ipaddress }} 'sudo cat /var/log/cloud-init-output.log && exit'
    - name: Delete temporary project & device
      uses: equinix-labs/metal-sweeper-action@main
      with:
        authToken: ${{ secrets.METAL_AUTH_TOKEN }}
        projectID: ${{ steps.metal-project.outputs.projectID }}
