name: 'equinix-metal-actions-example'

on:
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.METAL_PROJECT_ID }}
  PROJECT_TOKEN: ${{ secrets.METAL_PROJECT_TOKEN }}

jobs:
  project:
    runs-on: ubuntu-latest
    steps:
#    - name: Create temporary project
#      id: metal-project
#      uses: equinix-labs/metal-project-action@main
#      with:
#        userToken: ${{ secrets.METAL_AUTH_TOKEN }}
#        projectName: gsproject
#        organizationID: saravanan-org
#    - name: Use the Project SSH Key outputs (display it)
#      run: |
#        echo $PROJECT_PRIVATE_SSH_KEY
#        echo $PROJECT_PUBLIC_SSH_KEY
#      env:
#        PROJECT_PRIVATE_SSH_KEY: ${{ steps.metal-project.outputs.projectSSHPrivateKeyBase64 }}
#        PROJECT_PUBLIC_SSH_KEY: ${{ steps.metal-project.outputs.projectSSHPublicKey }}
#    - name: Use the Project ID outputs (display it)
#      run: |
#        echo Equinix Metal Project "$PROJECT_NAME" has ID "$PROJECT_ID"
#      env:
#        PROJECT_ID: ${{ steps.metal-project.outputs.projectID }}
#        PROJECT_NAME: ${{ steps.metal-project.outputs.projectName }}
    - name: Create device in temporary project
      uses: equinix-labs/metal-device-action@main
      continue-on-error: true
      with:
        metal_auth_token: $PROJECT_TOKEN
        metal_project_id: $PROJECT_ID
        metro: da
        plan: m3.small.x86
        os: ubuntu_22_04
    - name: Delete temporary project & device
      uses: equinix-labs/metal-sweeper-action@main
      with:
        authToken: $PROJECT_TOKEN
        projectID: $PROJECT_ID
